version: "2.1"
services:
    cardinal:
        container_name: cardinal
        environment:
            - REDDIT_API_CLIENT_ID=$REDDIT_API_CLIENT_ID
            - REDDIT_API_CLIENT_SECRET=$REDDIT_API_CLIENT_SECRET
            - REDDIT_API_CLIENT_USER=$REDDIT_API_CLIENT_USER
            - SUBREDDIT=$SUBREDDIT
            - CHANNEL=$CHANNEL
        build: .
        image: jmaguire/cardinal
        command: config/config.json
        volumes:
            - ./storage/:/usr/src/app/storage/
            - ./config/:/usr/src/app/config/
            - ./plugins/:/usr/src/app/plugins/
        restart: unless-stopped
